### ISSUE TITLE
Forward ENV vars to the remote process

### ISSUE THREAD

**Issue by chirino** [fabric8io/gosupervise#51]
Since config via env vars is a cornerstone of Docker/Kube config

**Comment by jstrachan** [comment]
isn't setting up of environment variables something that the Ansible playbook should do? 

the RC is really only about configuring the kansible pod

**Comment by chirino** [comment]
Yeah you probably right about this.  I was thinking about things like passing passwords to secure the jolokia configuration.  Might be better to pass that in env vars vs storing it on a disk file on the target or via a command line option that's visible to the 'ps' command.

**Comment by jstrachan** [comment]
Actually Secrets is a great idea! Being able to reuse Secrets from Kubernetes and scp them to the remote machines could be handy.

Though I guess folks manage secrets via Playbooks anyways?

**Comment by jstrachan** [comment]
for details see: https://github.com/fabric8io/kansible#kansible_export_env_vars

though I don't see a way for this to work with winrm yet :(
